name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      ip-addresses:
        description: 'Enter a comma-separated list of IP addresses to scan'
        required: true

jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nmapoption: ["-sn", "-F", "-sV","-O","-A","-p","-sU","-T4","-T3","-T2"]
    steps:
      
        - name: Install Nmap
          run: sudo apt-get install nmap
        - name: Scan IP with Nmap
          run: |
            IFS=',' read -ra ip_addresses <<< "${{ github.event.inputs.ip-addresses }}"
            for ip in "${ip_addresses[@]}"; do
            echo "Scanning IP: $ip"
            sudo nmap ${{ matrix.nmapoption }} "$ip"
            done
         
