name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      ip-addresses:
        description: 'Enter a comma-separated list of IP addresses to scan'
        required: true

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      
        - name: Install Nmap
          run: sudo apt-get install nmap
        - name: Scan IP with Nmap
          run: |
            IFS=',' read -ra ip_addresses <<< "${{ github.event.inputs.ip-addresses }}"
            for ip in "${ip_addresses[@]}"; do
            echo "Scanning IP: $ip"
            sudo nmap -sV -A -Pn "$ip"
            done
         
